#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/neuron/nrn-7.4"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/neuron/nrn-7.4/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/saray/TzilivakiEtal_FSBCs_model/Multicompartmental_Biophysical_models/mechanism/x86_64/.libs/libnrnmech.so" "$@"
